version: '3.8'

services:
  backtest-api:
    image: joshwatley/algotrade4j-backtest-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NEW_RELIC_APP_NAME=backtest-api-prod
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_LOG_FILE_NAME=STDOUT
      - MARKETDATA_API_KEY=${MARKETDATA_API_KEY}
      - MT5_API_URL=${MT5_API_URL}
      - MT5_API_KEY=${MT5_API_KEY}
      - TELEGRAM_SYSTEM_CHAT_ID=${TELEGRAM_SYSTEM_CHAT_ID}

  live-api:
    image: joshwatley/algotrade4j-live-api:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NEW_RELIC_APP_NAME=live-api-prod
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_LOG_FILE_NAME=STDOUT
      - DEFAULT_OANDA_ACCOUNT_ID=${DEFAULT_OANDA_ACCOUNT_ID}
      - MT5_API_URL=${MT5_API_URL}
      - MT5_API_KEY=${MT5_API_KEY}
      - TELEGRAM_SYSTEM_CHAT_ID=${TELEGRAM_SYSTEM_CHAT_ID}
      - SECURITY_ENCRYPTION_KEY=${SECURITY_ENCRYPTION_KEY}

  frontend:
    image: joshwatley/algotrade4j-frontend:latest
    ports:
      - "3000:80"

  newrelic-infra:
    build:
      context: .
      dockerfile: infra-config/newrelic-infra.dockerfile
    environment:
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped