version: '3.8'

services:
  api:
    image: joshwatley/algotrade4j-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
    entrypoint: >
      sh -c "java
      -XX:+UseG1GC 
      -XX:+UseStringDeduplication
      -jar /app/algotrade4j-api.jar"

  liveservice:
    image: joshwatley/algotrade4j-liveservice:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
    entrypoint: >
      sh -c "java
      -XX:+UseG1GC 
      -XX:+UseStringDeduplication
      -jar /app/algotrade4j-liveservice.jar"

  frontend:
    image: joshwatley/algotrade4j-frontend:latest
    ports:
      - "3000:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
    environment:
      - VITE_NODE_ENV=${VITE_NODE_ENV:-prod}
      - VITE_ENABLE_DEBUG_LOGS=${VITE_ENABLE_DEBUG_LOGS:-false}
      - VITE_ENABLE_SIGNUP=${VITE_ENABLE_SIGNUP:-false}
      - VITE_MAIN_API_HOST=${VITE_MAIN_API_HOST:-api.algotrade4j.trade}
      - VITE_LIVE_API_HOST=${VITE_LIVE_API_HOST:-live.algotrade4j.trade}

networks:
  default:
    driver: overlay