version: '3.8'

services:
  api:
    image: joshwatley/algotrade4j-api:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication
      - SPRING_PROFILES_ACTIVE=prod
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_SERVICE=algotrade4j-api-prod
      - DD_ENV=prod
      - DD_TAGS=env:prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
    entrypoint: >
      sh -c "java
      -javaagent:/app/dd-java-agent.jar 
      -XX:+UseG1GC 
      -XX:+UseStringDeduplication
      -Ddd.service=algotrade4j-api-prod
      -Ddd.env=prod 
      -Ddd.tags=env:prod 
      -Ddd.profiling-enabled=true
      -Ddd.logs.injection=true
      -Dcom.sun.management.jmxremote.debug=true 
      -Djava.rmi.server.hostname=0.0.0.0
      -Dcom.sun.management.jmxremote 
      -Dcom.sun.management.jmxremote.port=9010 
      -Dcom.sun.management.jmxremote.authenticate=false 
      -Dcom.sun.management.jmxremote.ssl=false 
      -jar /app/algotrade4j-api.jar"

  liveservice:
    image: joshwatley/algotrade4j-liveservice:latest
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication
      - SPRING_PROFILES_ACTIVE=prod
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_SERVICE=algotrade4j-liveservice-prod
      - DD_ENV=prod
      - DD_TAGS=env:prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
    entrypoint: >
      sh -c "java
      -javaagent:/app/dd-java-agent.jar 
      -XX:+UseG1GC 
      -XX:+UseStringDeduplication
      -Ddd.service=algotrade4j-liveservice-prod
      -Ddd.env=prod 
      -Ddd.tags=env:prod 
      -Ddd.profiling-enabled=true
      -Ddd.logs.injection=true
      -Dcom.sun.management.jmxremote.debug=true 
      -Djava.rmi.server.hostname=0.0.0.0
      -Dcom.sun.management.jmxremote 
      -Dcom.sun.management.jmxremote.port=9011 
      -Dcom.sun.management.jmxremote.authenticate=false 
      -Dcom.sun.management.jmxremote.ssl=false 
      -jar /app/algotrade4j-liveservice.jar"

  frontend:
    image: joshwatley/algotrade4j-frontend:latest
    ports:
      - "3000:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
    environment:
      - VITE_NODE_ENV=${VITE_NODE_ENV:-prod}
      - VITE_ENABLE_DEBUG_LOGS=${VITE_ENABLE_DEBUG_LOGS:-false}
      - VITE_ENABLE_SIGNUP=${VITE_ENABLE_SIGNUP:-false}
      - VITE_MAIN_API_HOST=${VITE_MAIN_API_HOST:-api}
      - VITE_LIVE_API_HOST=${VITE_LIVE_API_HOST:-liveservice}

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_ENV=prod
      - DD_SITE=datadoghq.eu
      - DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
    ports:
      - "8126:8126"
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      - VITE_MAIN_API_HOST=${VITE_MAIN_API_HOST:-api.algotrade4j.trade}
      - VITE_LIVE_API_HOST=${VITE_LIVE_API_HOST:-live.algotrade4j.trade}

networks:
  default:
    driver: overlay