version: '3.8'

services:
  backtest-api:
    image: joshwatley/algotrade4j-backtest-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    entrypoint: >
      sh -c "java
      -jar /app/algotrade4j-backtest-api.jar"

  live-api:
    image: joshwatley/algotrade4j-live-api:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OANDA_API_URL=${OANDA_API_URL}
      - OANDA_API_KEY=${OANDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - ADDITIONAL_JAVA_OPTS=${ADDITIONAL_JAVA_OPTS}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    entrypoint: >
      sh -c "java
      -jar /app/algotrade4j-live-api.jar"

  frontend:
    image: joshwatley/algotrade4j-frontend:latest
    ports:
      - "3000:80"