/** @type {import('prettier').Config} */
const config = {
  endOfLine: 'lf',
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  importOrderSeparation: false,
  printWidth: 120,
  importOrder: [
    '^node:$',
    '',
    '^(react/(.*)$)|^(react$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/types$',
    '^@/types/(.*)$',
    '^@/config$',
    '^@/config/(.*)$',
    '^@/paths$',
    '^@/routes$',
    '^@/root$',
    '^@/pages/(.*)$',
    '^@/data/(.*)$',
    '^@/lib/(.*)$',
    '^@/locales/(.*)$',
    '^@/contexts/(.*)$',
    '^@/hooks/(.*)$',
    '^@/components/(.*)$',
    '^@/styles/(.*)$',
    '',
    '^[./]',
  ],
};

export default config;
