package dev.jwtly10.shared.tracking;

public enum UserAction {
    LOGIN,
    LOGOUT,

    BACKTEST_RUN,

    OPTIMISATION_RUN,
    OPTIMISATION_RESULTS,
    OPTIMISATION_DELETE,

    LIVE_STRATEGY_CREATE,
    LIVE_STRATEGY_EDIT,
    LIVE_STRATEGY_TOGGLE,
    LIVE_STRATEGY_DELETE,

    BROKER_ACCOUNT_CREATE,
    BROKER_ACCOUNT_EDIT,
    BROKER_ACCOUNT_TOGGLE,
}