name: Main Branch CI - Run Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn clean test

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload java artifacts to remote
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #          passphrase: ${{ secrets.PASSWORD }}
          #          password: ${{ secrets.PASSWORD }}
          source: "algotrade4j-api/target/*.jar"
          target: "/opt/algotrade4j"

      - name: Upload dockerfiles to remote
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #          passphrase: ${{ secrets.PASSWORD }}
          #          password: ${{ secrets.PASSWORD }}
          source: "Dockerfile, docker-compose.yml"
          target: "/opt/algotrade4j"

      - name: Run docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #          passphrase: ${{ secrets.PASSWORD }}
          script: |
            cd /opt/algotrade4j &&
            OANDA_API_URL=${{vars.OANDA_API_URL}} \
            OANDA_API_KEY=${{secrets.OANDA_API_KEY}} \
            OANDA_ACCOUNT_ID=${{secrets.OANDA_ACCOUNT_ID}} \
            JWT_SECRET=${{secrets.JWT_SECRET}} \
            SPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}} \
            SPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_USERNAME}} \
            SPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}} \
            ADDITIONAL_JAVA_OPTS=${{vars.ADDITIONAL_JAVA_OPTS}} \
            DD_API_KEY=${{secrets.DD_API_KEY}} \
            docker-compose up -d --build